SesacDTeam/swim-done

frontend/package-lock.json
frontend/package.json
frontend/vite.config.js

- 배포설정 추가함 (`npm install vite-plugin-compression --save`)
- 메인브랜치 최신화 이후 `npm install` 실행

[SW-14] chore: gzip 설정

---

backend/src/main/java/com/done/swim/domain/swimmingtime/repository/SwimmingTimeRepository.java

- ISSUE-21
- SwimmingTimeRepository JpaRepository 제네릭 타임 설정 에러 수정
- [ x] Jira 이슈 상태 업데이트

[SW-21] fix: SwimmingTimeRepository 에러 수정

---

frontend/src/components/sociallogin/KakaoLoginButton.jsx
frontend/src/components/sociallogin/KakaoRedirectHandler.js
frontend/src/pages/Login.jsx

[SW-17] feat: 카카오톡 소셜로그인 버튼 구현

---

backend/.gitignore
backend/compose.yaml

- SW-16
- db compose 파일 수정
- csv 파일 BE 파일 루트에 붙여넣기 후 아래 쿼리 날리면 적용됩니다.
```
LOAD DATA INFILE '/var/lib/mysql-files/pools_data.csv'
REPLACE
INTO TABLE pools
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(address, section, parking, link, name, latitude, longitude);
```

[SW-16] chore: 수영장 데이터 저장 세팅

---

backend/src/main/java/com/done/swim/domain/poolmark/controller/PoolMarkController.java
backend/src/main/java/com/done/swim/domain/poolmark/dto/PoolMarkListResponseDto.java
backend/src/main/java/com/done/swim/domain/poolmark/dto/PoolMarkResponseDto.java
backend/src/main/java/com/done/swim/domain/poolmark/entity/PoolMark.java
backend/src/main/java/com/done/swim/domain/poolmark/repository/PoolMarkRepository.java
backend/src/main/java/com/done/swim/domain/poolmark/service/PoolMarkService.java
backend/src/main/resources/application.properties

- SW-36
- Repository, Service, Controller 찜 목록 조회 메서드 구현
- Pagination 구현

[SW-36] 찜목록 조회 api 구현

---

backend/src/main/java/com/done/swim/domain/poolmark/controller/PoolMarkController.java
backend/src/main/java/com/done/swim/domain/poolmark/dto/PoolMarkResponseDto.java
backend/src/main/java/com/done/swim/domain/poolmark/repository/PoolMarkRepository.java
backend/src/main/java/com/done/swim/domain/poolmark/service/PoolMarkService.java

- SW-42
- Repository, Service, Controller 찜 삭제 메서드 구현

[SW-42] feat: 찜목록 삭제 api 구현

---

backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
backend/src/main/java/com/done/swim/domain/poolreview/dto/requestdto/UpdatePoolReviewRequestDto.java
backend/src/main/java/com/done/swim/domain/poolreview/dto/responsedto/UpdatePoolReviewResponseDto.java
backend/src/main/java/com/done/swim/domain/poolreview/entity/PoolReview.java
backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java

- SW-47
- PoolReviewController => updateReview 추가
- PoolReviewService => updateReview 추가
- requestdto => UpdatePoolReviewRequestDto 추가
- requestdto => UpdatePoolReviewResponseDto 추가
- [✅] 커밋 메시지에 Jira 이슈 번호 포함
- 포스트맨 테스트 결과 보여지는 updateAt은 이전 정보이나 데이터베이스에는 정상적으로 변경시간으로 변경됨 확인했습니다.

[SW-47] feat: 리뷰 수정 API 구현

---

backend/.env.example
backend/build.gradle
backend/src/main/java/com/done/swim/config/SecurityConfig.java
backend/src/main/java/com/done/swim/domain/user/entity/User.java
backend/src/main/java/com/done/swim/global/jwt/CustomUserDetailsService.java
backend/src/main/java/com/done/swim/global/jwt/JwtAuthenticationFilter.java
backend/src/main/java/com/done/swim/global/jwt/JwtTokenProvider.java
backend/src/main/java/com/done/swim/global/security/handler/CustomAccessDeniedHandler.java
backend/src/main/java/com/done/swim/global/security/handler/JwtAuthenticationEntryPoint.java
backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2User.java
backend/src/main/java/com/done/swim/sociallogin/CustomOAuth2UserService.java
backend/src/main/java/com/done/swim/sociallogin/OAuth2LoginSuccessHandler.java
backend/src/main/java/com/done/swim/sociallogin/OAuth2TokenService.java
backend/src/main/java/com/done/swim/sociallogin/TokenController.java
backend/src/main/java/com/done/swim/sociallogin/provider/KakaoUserInfo.java
backend/src/main/java/com/done/swim/sociallogin/provider/NaverUserInfo.java
backend/src/main/java/com/done/swim/sociallogin/provider/OAuth2UserInfo.java
backend/src/main/java/com/done/swim/sociallogin/provider/Provider.java
backend/src/main/resources/application.properties

- ISSUE-39
- 시큐리티 설정 로직 추가
- 토큰 생성 로직 추가
- redis, 쿠키 사용
- 로그아웃 추후 추가 예정

[SW-39] feat: 네이버 소셜로그인 백엔드 로직 기능 구현 추가

---

backend/src/main/java/com/done/swim/domain/poolreview/controller/PoolReviewController.java
backend/src/main/java/com/done/swim/domain/poolreview/dto/requestdto/CreatePoolReviewRequestDto.java
backend/src/main/java/com/done/swim/domain/poolreview/repository/PoolReviewRepository.java
backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java

- SW-41
- Controller에 @AuthenticationPrincipal 추가
- [✅] 커밋 메시지에 Jira 이슈 번호 포함
- [✅] 로컬에서 출동확인
-

Feat/sw 41 be 나의 리뷰 조회 api 구현

---

frontend/src/pages/NotFound.jsx
frontend/src/router/index.jsx

- SW-64
- NotFound 컴포넌트 구현
- router index.jsx 수정

[SW-64] 라우터 에러페이지 구현

---

frontend/src/api/authApi.js
frontend/src/api/axios.js
frontend/src/api/reviewApi.js
frontend/src/components/common/createreview/CreateReview.jsx
frontend/src/components/common/pooldetail/PoolDetail.jsx

- ISSUE-59
- 리뷰 작성 페이지 구조 세팅
- CSS 작업
- 백엔드와 연결
-

[SW-59] 리뷰 작성 페이지 구현

---

frontend/templates/https.conf.template
frontend/vite.config.js

[SW-75] chore: fix nginx.conf

---

backend/src/main/java/com/done/swim/oauth2/CustomOAuth2UserService.java
backend/src/main/java/com/done/swim/oauth2/provider/GithubUserInfo.java
frontend/src/components/common/pooldetail/PoolDetail.jsx
frontend/src/pages/Login.jsx

- ISSUE-80
- 닉네임 자체가 없어서 id를 닉네임으로 가져옴
(마이페이지에서 깃허브id를 닉네임으로 사용)
-

[SW-80] feat: 깃허브 소셜로그인 닉네임 가져오기

---

.idea/vcs.xml
backend/src/main/java/com/done/swim/domain/submittedimage/service/SubmittedImageService.java
frontend/src/components/common/createreview/CreateReview.jsx
frontend/src/components/common/pooldetail/PoolDetail.jsx
frontend/src/components/common/pooldetail/TimeTable.jsx
frontend/src/components/common/submittedImage/SubmittedImage.jsx
frontend/src/error/ErrorBoundary.jsx
frontend/src/hooks/useErrorResolver.jsx

- SW-87
- 타임테이블 디자인
- 로직 주말에 구현 예정

[SW-89] design: 디테일뷰

---

frontend/src/components/mypage/MyPage.jsx
frontend/src/router/index.jsx

- SW-93
- MyPage.jsx에 error 관련 코드들 추가
- router에 코드 추가
- [✅] 커밋 메시지에 Jira 이슈 번호 포함
-

[SW-93] 마이페이지 error페이지 이동 로직 추가

---

backend/src/main/java/com/done/swim/domain/poolreview/service/PoolReviewService.java

- SW-95
- PoolReviewService 에러 수정

[SW-95] PoolReviewService 에러 수정

---

frontend/src/components/common/DetailViewHeader.jsx
frontend/src/components/common/pooldetail/PoolDetail.jsx
frontend/src/components/mypage/MyPage.jsx
frontend/src/components/mypage/MyPageItem.jsx
frontend/src/components/mypage/MyReviewPage.jsx
frontend/src/components/mypage/MyReviewPageItem.jsx
frontend/src/router/index.jsx

- SW-96
- 나의 리뷰 페이지 뒤로가기 수정
- 디테일 뷰 헤더 레이아웃 수정

[SW-96] 리뷰 수정 생성 페이지 로직 수정

---

frontend/src/components/kakaomap/KakaoMapContainer.jsx
frontend/src/components/mypage/MyPage.jsx

- 중복으로 인한 에러 처리
- 지도 마커 이벤트 에러 처리
- 
-

[SW-106] fix: 코드 에러 처리

---

frontend/src/components/kakaomap/KakaoMapContainer.jsx
frontend/src/error/ErrorBoundary.jsx
frontend/src/hooks/useErrorResolver.jsx

마커 오류 시 토스트로 대체
폴리곤 토스트 멘트 수정
-SW-104
- 마커 오류 시 토스트로 대체
- 폴리곤 토스트 멘트 수정

[SW-104] 마커 오류 토스트 추가

---

frontend/src/components/common/review/CreateReview.jsx
frontend/src/components/common/review/UpdateReview.jsx
frontend/src/error/ErrorCatcher.jsx
frontend/src/hooks/useErrorResolver.jsx
frontend/src/hooks/useSubmitReview.jsx

- SW-109
- 리뷰 작성, 수정 페이지 에러 수정
- ErrorCatcher 재 렌더링 방지

[SW-109] 리뷰 작성 수정 페이지 에러 수정

---

frontend/src/components/common/review/CreateReview.jsx
frontend/src/components/mypage/MyPage.jsx
frontend/src/components/mypage/MyReviewPageItem.jsx

[SW-108] fix: 알림창 토스트로 변경

---

frontend/src/components/common/AlertModal.jsx

- ISSUE-112
- AlertModal에서 엔터키 방지 로직 추가
-

[SW-112] feat: 리뷰 작성 후 엔터 클릭시 리뷰 중복 생성 막음

---

frontend/src/components/common/LoadingSpinner.jsx

- SW-114
- LoadingSpinner 파일 이름 수정

[SW-114] 배포 에러 수정

---

frontend/src/components/markpools/MarkPools.jsx
frontend/src/error/ErrorBoundary.jsx
frontend/src/hooks/useErrorResolver.jsx

- SW-115
- error boundary 재시도 구현
- unknow error 로직 추가
-

[SW-115] error boundary 재시도 구현

---

frontend/src/components/sociallogin/GithubLoginButton.jsx
frontend/src/components/sociallogin/KakaoLoginButton.jsx
frontend/src/components/sociallogin/NaverLoginButton.jsx
frontend/src/components/sociallogin/RecentLoginLabel.jsx
frontend/src/pages/Login.jsx

- ISSUE-116
- 최근 로그인 이력 RecentLoginLabel 컴포넌트로 분리
- 깃허브 로그인 버튼 크기 조정
-

[SW-116] refactor: 최근 로그인 이력 컴포넌트로 분리

---

frontend/src/components/mypage/MyReviewPage.jsx
frontend/src/components/mypage/MyReviewPageItem.jsx
frontend/src/error/ErrorBoundary.jsx
frontend/src/pages/Login.jsx

- SW-117
- 기존 infiniteScroll => useInfiniteScroll 형식으로 변환
- 삭제시 로직 변경
- 에러페이지 이모지 수정
-

[SW-117] fix: 리뷰 삭제시 발생하는 오류 해결

---

backend/src/main/java/com/done/swim/oauth2/handler/OAuth2LoginSuccessHandler.java
backend/src/main/java/com/done/swim/oauth2/service/OAuth2TokenService.java

[SW-124] 리프레시 토큰 저장 로직 재수정

---

frontend/src/components/common/LoadingSpinner.jsx

- ISSUE-125
- 로딩 중 이미지 풀부이 변경
-

[SW-125] design: 로딩중 이미지 풀부이 변경

---

frontend/src/components/common/loadingSpinner.jsx

[SW-126] 충동 해결용

---

frontend/src/components/common/submittedImage/SubmittedImage.jsx

- SW-131
- 이미지 제보 후 navigate 경로 수정

[SW-131] 이미지 제출 후 navigate 경로 수정

---

frontend/src/components/common/AlertModal.jsx
frontend/src/components/common/LoadingSpinner.jsx
frontend/src/components/common/pooldetail/PoolDetail.jsx
frontend/src/components/common/review/CreateReview.jsx
frontend/src/components/common/review/UpdateReview.jsx
frontend/src/components/common/submittedImage/SubmittedImage.jsx
frontend/src/components/mypage/MyPage.jsx
frontend/src/components/mypage/MyReviewPage.jsx
frontend/src/components/mypage/MyReviewPageItem.jsx

- SW-133
- 리뷰 생성페이지 로딩 스피너 구현
- 리뷰 수정페이지 로딩 스피너 구현
- 이미지 제보페이지 로딩 스피너 구현
- 로딩 스피너 배경색 커스텀 할 수 있도록 수정
- 드롭다운 색 변경
- 로그아웃, 회원 탈퇴 로딩 스피너 alert 구현

[SW-133] 리뷰작성 제보하기 로딩 구현

---

frontend/src/components/common/submittedImage/SubmittedImage.jsx
frontend/src/components/mypage/MyPage.jsx
frontend/src/components/sidebar/SideBar.jsx

[SW-135] 제보하기 로딩처리 에러 수정

---

frontend/src/components/common/AlertModal.jsx
frontend/src/components/common/MainBanner.jsx
frontend/src/components/common/pooldetail/PoolDetail.jsx
frontend/src/components/common/pooldetail/TimeTable.jsx
frontend/src/components/mypage/MyPage.jsx
frontend/src/index.css
frontend/src/pages/Home.jsx

- ISSUE-134
- 메인 화면 배너 추가
- CSS 조정 (텍스트,  버튼 등 간격 및 위치 조정, 커서 포인터 통일)
-

[SW-134] 메인 페이지 알림 추가

---

README.md

[SW-138] 시연영상 추가
